version: '3.8'

networks:
  app_net:
    external: true
    name: app_net
  web_net:
    external: true
    name: web_net

volumes:
  loki_data:
    name: loki_data

services:
  loki:
    image: grafana/loki:k171-b5eaae1
    command: -config.file=/etc/loki/loki.yml
    restart: ${RESTART_POLICY}
    container_name: loki
    user: root
    volumes:
      - loki_data:/tmp/loki
      - ./loki:/etc/loki/
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.loki.entrypoints=http
      - traefik.http.routers.loki.rule=Host(`${LOGSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.loki.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.loki-secure.entrypoints=https
      - traefik.http.routers.loki-secure.rule=Host(`${LOGSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.loki-secure.tls=true
      - traefik.http.routers.loki-secure.tls.options=default
      - traefik.http.routers.loki-secure.middlewares=web-auth
      - traefik.http.routers.loki-secure.tls.certresolver=mycert
      - traefik.http.services.loki.loadbalancer.server.port=3100

  promtail:
    image: grafana/promtail:k171-b5eaae1
    restart: ${RESTART_POLICY}
    hostname: promtail-${HOSTNAME}
    container_name: promtail-${HOSTNAME}
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail:/etc/promtail/
    command: -config.file=/etc/promtail/promtail.yml --client.external-labels=host=${HOSTNAME}
    networks:
      - app_net