---
controller:
  replicaCount: 3   # ingress nginx controller replica count
  minAvailable: 1   # ingress nginx controller minimum available count
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 90Mi

  service:
    externalTrafficPolicy: Local
    nodePorts:
      http: 32080   # Haproxy backend port for http
      https: 32443  # Haproxy backend port for https
    type: NodePort

  metrics:
    port: 10254
    enabled: true
    service:
      type: NodePort
      nodePort: "32254"
