version: '3.8'

networks:
  app_net:
    external: true
    name: app_net
  web_net:
    external: true
    name: web_net

volumes:
  grafana_data:
    name: grafana_data
  prometheus_data:
    name: prometheus_data
  alertmanager_data:
    name: alertmanager_data
  pushgateway_data:
    name: pushgateway_data

services:
  prometheus:
    image: prom/prometheus:v2.47.1
    restart: ${RESTART_POLICY}
    container_name: prometeheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --storage.tsdb.retention.size=150GB
      - --web.enable-remote-write-receiver
      - --web.enable-lifecycle
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.prometheus.entrypoints=http
      - traefik.http.routers.prometheus.rule=Host(`${PROSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.prometheus.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.prometheus-secure.entrypoints=https
      - traefik.http.routers.prometheus-secure.rule=Host(`${PROSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.prometheus-secure.tls=true
      - traefik.http.routers.prometheus-secure.tls.options=default
      - traefik.http.routers.prometheus-secure.middlewares=web-auth
      - traefik.http.routers.prometheus-secure.tls.certresolver=mycert
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

  grafana:
    image: grafana/grafana:10.1.5
    restart: ${RESTART_POLICY}
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      #- GF_INSTALL_PLUGINS=${GRAFANA_INSTALL_PLUGINS}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_USERS_DEFAULT_THEME=light
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.grafana.entrypoints=http
      - traefik.http.routers.grafana.rule=Host(`${GRASUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.grafana.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.grafana-secure.entrypoints=https
      - traefik.http.routers.grafana-secure.rule=Host(`${GRASUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.grafana-secure.tls=true
      - traefik.http.routers.grafana-secure.tls.options=default
      - traefik.http.routers.grafana-secure.tls.certresolver=mycert
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  alertmanager:
    image: prom/alertmanager:v0.26.0
    restart: ${RESTART_POLICY}
    container_name: alertmanager
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.alert.entrypoints=http
      - traefik.http.routers.alert.rule=Host(`${ALESUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.alert.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.alert-secure.entrypoints=https
      - traefik.http.routers.alert-secure.rule=Host(`${ALESUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.alert-secure.tls=true
      - traefik.http.routers.alert-secure.tls.options=default
      - traefik.http.routers.alert-secure.middlewares=web-auth
      - traefik.http.routers.alert-secure.tls.certresolver=mycert
      - traefik.http.services.alert.loadbalancer.server.port=9093

  pushgateway:
    image: prom/pushgateway:v1.6.2
    restart: ${RESTART_POLICY}
    container_name: pushgateway
    command:
      - --persistence.file=/tmp/pushgateway.store
      - --persistence.interval=1m
    volumes:
      - pushgateway_data:/tmp/
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.push.entrypoints=http
      - traefik.http.routers.push.rule=Host(`${PGWSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.push.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.push-secure.entrypoints=https
      - traefik.http.routers.push-secure.rule=Host(`${PGWSUB}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.push-secure.tls=true
      - traefik.http.routers.push-secure.tls.options=default
      - traefik.http.routers.push-secure.middlewares=web-auth
      - traefik.http.routers.push-secure.tls.certresolver=mycert
      - traefik.http.services.push.loadbalancer.server.port=9091

  cadvisor:
    image: docker.io/ahmadrafiee/cadvisor
    command: --disable_metrics=disk,udp,percpu
    restart: ${RESTART_POLICY}
    hostname: '${HOSTNAME}'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.cadvisor.entrypoints=http
      - traefik.http.routers.cadvisor.rule=Host(`${CONTAINER_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.cadvisor.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.cadvisor-secure.entrypoints=https
      - traefik.http.routers.cadvisor-secure.rule=Host(`${CONTAINER_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.cadvisor-secure.tls=true
      - traefik.http.routers.cadvisor-secure.tls.options=default
      - traefik.http.routers.cadvisor-secure.middlewares=web-auth
      - traefik.http.routers.cadvisor-secure.tls.certresolver=mycert
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.24.0
    restart: ${RESTART_POLICY}
    hostname: '${HOSTNAME}'
    container_name: blackbox-exporter
    command:
      - '--config.file=/etc/blackboxexporter/blackbox-exporter.yml'
    volumes:
      - ./blackbox:/etc/blackboxexporter
    networks:
      - app_net

  node-exporter:
    image: prom/node-exporter:v1.6.1
    restart: ${RESTART_POLICY}
    hostname: '${HOSTNAME}'
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - web_net
      - app_net
    labels:
      - traefik.enable=true
      - traefik.docker.network=web_net
      - traefik.http.routers.node-exporter.entrypoints=http
      - traefik.http.routers.node-exporter.rule=Host(`${NODE_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.node-exporter.middlewares=https-redirect
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.node-exporter-secure.entrypoints=https
      - traefik.http.routers.node-exporter-secure.rule=Host(`${NODE_SUB_DOMAIN}.${DOMAIN_ADDRESS}`)
      - traefik.http.routers.node-exporter-secure.tls=true
      - traefik.http.routers.node-exporter-secure.tls.options=default
      - traefik.http.routers.node-exporter-secure.middlewares=web-auth
      - traefik.http.routers.node-exporter-secure.tls.certresolver=mycert
      - traefik.http.services.node-exporter.loadbalancer.server.port=9100
