version: '3.8'

networks:
  web_net:
    name: web_net
    external: true
  app_net:
    name: app_net
    external: true

volumes:
  runner_data:
    name: runner_data
    external: false

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-v16.5.0
    restart: unless-stopped
    container_name: gitlab-runner
    hostname: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/etc/gitlab-runner
    networks:
      - app_net
      - web_net